# Generated by Django 4.2.30 on 2026-07-03 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('merchant', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Utility', 'Utility'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('receipt', 'Receipt'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
